### ISSUE TITLE
[Feat][Customer Request] Develop Ansible module for NGT installation/upgrade for User VMs

### ISSUE THREAD

**Issue by varunbs** [nutanix/nutanix.ansible#210]
Requirements:
- Customer has a requirement of Ansible playbook that will perform installation/upgrade of NGT for User VMs  
- The request is to develop a ansible playbook that will do a NGT lifecycle management for the user VMs        

Todo:
- [x] Client SDK, get_spec()
- [x] Ansible spec & spec validator
- [ ] Unit test, sanity test
- [x] Integration test
- [x] Documentation
- [x] Examples

**Comment by varunbs** [comment]
Creating this request from Blue Yonder customer

**Comment by bhati-pradeep** [comment]
Related APIs for development of this feature:
1. /api/nutanix/v3/vms/
2. /api/nutanix/v3/ngt_policies

Refer Docs:
https://www.nutanix.dev/api_references/prism-central-v3/#/f334f014089fa-create-a-new-ngt-policy
https://www.nutanix.dev/api_references/prism-central-v3/#/a140c4acd95f6-update-an-existing-vm

**Comment by bhati-pradeep** [comment]
Released in v2.0.0 :
[ntnx_vms_ngt_info_v2](https://galaxy.ansible.com/ui/repo/published/nutanix/ncp/content/module/ntnx_vms_ngt_info_v2/)
[ntnx_vms_ngt_insert_iso_v2](https://galaxy.ansible.com/ui/repo/published/nutanix/ncp/content/module/ntnx_vms_ngt_insert_iso_v2/)
[ntnx_vms_ngt_update_v2](https://galaxy.ansible.com/ui/repo/published/nutanix/ncp/content/module/ntnx_vms_ngt_update_v2/)
[ntnx_vms_ngt_upgrade_v2](https://galaxy.ansible.com/ui/repo/published/nutanix/ncp/content/module/ntnx_vms_ngt_upgrade_v2/)
[ntnx_vms_ngt_v2](https://galaxy.ansible.com/ui/repo/published/nutanix/ncp/content/module/ntnx_vms_ngt_v2/)

**Comment by fabriceverkor** [comment]
I just installed 2.0.0 version and tried nutanix.ncp.ntnx_vms_ngt_v2 module to install NGT tools on a VM.
I get error message below
I says I'm missing ntnx_vmm_py_client python module ....
But I don't see in https://galaxy.ansible.com/ui/repo/published/nutanix/ncp/docs/ any related requirements
What am I missing ?

The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_nutanix.ncp.ntnx_vms_ngt_v2_payload_1r99t84c/ansible_nutanix.ncp.ntnx_vms_ngt_v2_payload.zip/ansible_collections/nutanix/ncp/plugins/modules/ntnx_vms_ngt_v2.py", line 184, in <module>
ModuleNotFoundError: No module named 'ntnx_vmm_py_client'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "capabilities": null,
            "credential": null,
            "ext_id": "7b4ece2e-e9d5-4cb3-884d-57f5ed9f6b64",
            "nutanix_host": "prismcentral.inf.idz.vic.verkor.com",
            "nutanix_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "nutanix_port": "9440",
            "nutanix_username": "admin",
            "reboot_preference": null,
            "state": "present",
            "validate_certs": false,
            "wait": true
        }
    },
    "msg": "Failed to import the required Python library (ntnx_vmm_py_client) on iac-dev's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"
}

**Comment by fabriceverkor** [comment]
Hello
Thank you for you answer

ansible --version gives :
ansible [core 2.16.10]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /etc/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.2 (main, Nov 30 2024, 21:22:50) [GCC 12.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True


Which requirements.txt file are you talking about ? 
I don't see it in  https://galaxy.ansible.com/ui/repo/published/nutanix/ncp/docs/.
Thanks

**Comment by bhati-pradeep** [comment]
hey @fabriceverkor. You can download this [requirements](https://github.com/nutanix/nutanix.ansible/blob/main/requirements.txt) using the interpreter used by ansible to run your playbook `/usr/bin/python3`

**Comment by fabriceverkor** [comment]
OK. PIP requirements installed.
But where is it specified in your docs ?
Then next step : as module requires ext_id instead of usual VM uuid? I have to get it with  code below :
    - name: Get VM infos v2
      nutanix.ncp.ntnx_vms_info_v2:
        filter:
          vm_name: "{{ fqdn }}"
      register: vm_result2
      tags: always

But I get following error :

The full traceback is:
  File "/tmp/ansible_nutanix.ncp.ntnx_vms_info_v2_payload_8yewhfmy/ansible_nutanix.ncp.ntnx_vms_info_v2_payload.zip/ansible_collections/nutanix/ncp/plugins/modules/ntnx_vms_info_v2.py", line 178, in get_vms
  File "/usr/local/lib/python3.11/dist-packages/ntnx_vmm_py_client/api/vm_api.py", line 4818, in list_vms
    (data) = self.api_client._call_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/ntnx_vmm_py_client/api_client.py", line 992, in _call_api
    return self.__call_api(resource_path, method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/ntnx_vmm_py_client/api_client.py", line 758, in __call_api
    response_data = self.request(
                    ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/ntnx_vmm_py_client/api_client.py", line 1017, in request
    return self.rest_client.GET(url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/ntnx_vmm_py_client/rest.py", line 329, in GET
    return self.request("GET", url,
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/ntnx_vmm_py_client/rest.py", line 323, in request
    raise ApiException(http_resp=r)
fatal: [localhost]: FAILED! => {
    "changed": false,
    "error": "NOT FOUND",
    "invocation": {
        "module_args": {
            "filter": "{'vm_name': 'myvm'}",
            "nutanix_host": "myprism",
            "nutanix_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "nutanix_port": "9440",
            "nutanix_username": "admin",
            "validate_certs": false
        }
    },
    "msg": "Api Exception raised while fetching vms info",
    "response": {
        "message": "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."
    },
    "status": 404
}

**Comment by bhati-pradeep** [comment]
Hi @fabriceverkor 

> But where is it specified in your docs ?
This requirements are installed when you install nutanix.ncp using galaxy. But there is some issue with python interpreter used for playbook run. Thats why I asked for installing it seperatly.

> About this error you are facing:
Seems the api is missing from the server, can you please provide this information to me :
- PC version
- Output of `pip freeze | grep ntnx-`

**Comment by fabriceverkor** [comment]
Hi
pip freeze|g ntnx gives :
ntnx-clustermgmt-py-client==4.0.1
ntnx-dataprotection-py-client==4.0.1
ntnx-iam-py-client==4.0.1
ntnx-microseg-py-client==4.0.1
ntnx-networking-py-client==4.0.1
ntnx-prism-py-client==4.0.1
ntnx-vmm-py-client==4.0.1
ntnx-volumes-py-client==4.0.1

**Comment by fabriceverkor** [comment]
Indeed, when using prismcentral as prism host, i get output below.
But is it not because our AOS version 6.1, not 7, cf https://github.com/nutanix/nutanix.ansible#releases ?


fatal: [localhost]: FAILED! => {
    "changed": false,
    "error": "INTERNAL SERVER ERROR",
    "invocation": {
        "module_args": {
            "filter": "{'vm_name': 'myvm'}",
            "nutanix_host": "myprismcentral",
            "nutanix_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "nutanix_port": "9440",
            "nutanix_username": "admin",
            "validate_certs": false
        }
    },
    "msg": "Api Exception raised while fetching vms info",
    "response": {
        "$dataItemDiscriminator": "vmm.v4.error.ErrorResponse",
        "data": {
            "$objectType": "vmm.v4.error.ErrorResponse",
            "error": [
                {
                    "$objectType": "vmm.v4.error.AppMessage",
                    "code": "PLAT-10006",
                    "errorGroup": "INTERNAL_ERROR",
                    "locale": "en_US",
                    "message": "Failed to perform the operation due to an internal error.",
                    "severity": "ERROR"
                }
            ]
        }
    },
    "status": 500
}
